#!/bin/bash

# $1 is the first variable which is also your project's name.
# Make sure the user provides a name for the project
if [[ "$1" == "" ]]; then
  echo "Please enter a name for the project!"
  exit 1
fi

# Make sure there is no existing project with the same name

if [[ -d $1.Solution ]]; then
  echo "Project already exists!"
  exit 1
fi

# Set up project 
mkdir $1.Solution
mkdir $1.Solution/$1 
mkdir $1.Solution/$1/Models
touch $1.Solution/$1/$1.csproj
touch $1.Solution/$1/Models/$1.cs
mkdir $1.Solution/$1.Tests 
mkdir $1.Solution/$1.Tests/ModelTests
touch $1.Solution/$1.Tests/$1.Tests.csproj
touch $1.Solution/$1.Tests/ModelTests/$1Tests.cs
touch $1.Solution/README.md

# Write to .csproj files
/bin/cat <<EOM >$1.Solution/$1/$1.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
  </ItemGroup>
</Project>
EOM

/bin/cat <<EOM >$1.Solution/$1.Tests/$1.Tests.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../$1/$1.csproj" />
  </ItemGroup>
</Project>
EOM

#Restore dependencies
cd $1.Solution/$1.Tests
dotnet restore

#Create .gitignore
/bin/cat <<EOM >$1.Solution/.gitignore
# Compiled source #
###################
*.com
*.class
*.dll
*.exe
*.o
*.so

# Packages #
############
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Logs and databases #
######################
*.log
*.sql
*.sqlite

# OS generated files #
######################
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Csharp generated files #
.vscode
bin/
obj/
EOM

#Initialize Git
cd ..
git init
